# Generated by Django 4.2.11 on 2026-01-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('PATIENT', 'Patient')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('component_type', models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLT', 'Platelets'), ('PLS', 'Plasma')], max_length=3)),
                ('units_needed', models.PositiveIntegerField()),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
    ]
