# Generated by Django 6.1 on 2026-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=15)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
